export const FETCH_NEWS_LIST = 'FETCH_NEWS_LIST';
export const EMPTY_NEWS_LIST = 'EMPTY_NEWS_LIST';
export const UPDATE_QUERY = 'UPDATE_QUERY';
export const UPDATE_PAGE = 'UPDATE_PAGE';
export const UPDATE_LOADING = 'UPDATE_LOADING';
export const UPDATE_PAGINATION = 'UPDATE_PAGINATION';